// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: toise/v1/events.proto

package toisev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChangeType classifies an event per the Toise change taxonomy. See ADR 0006.
type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED                ChangeType = 0
	ChangeType_CHANGE_TYPE_ENTITY_CREATED             ChangeType = 1
	ChangeType_CHANGE_TYPE_ENTITY_DELETED             ChangeType = 2
	ChangeType_CHANGE_TYPE_ENTITY_IDENTITY_CHANGED    ChangeType = 3
	ChangeType_CHANGE_TYPE_ENTITY_ATTRIBUTE_UPDATED   ChangeType = 4
	ChangeType_CHANGE_TYPE_ENTITY_STATE_CHANGED       ChangeType = 5
	ChangeType_CHANGE_TYPE_ENTITY_UNCHANGED           ChangeType = 6
	ChangeType_CHANGE_TYPE_RELATION_ADDED             ChangeType = 7
	ChangeType_CHANGE_TYPE_RELATION_REMOVED           ChangeType = 8
	ChangeType_CHANGE_TYPE_RELATION_ATTRIBUTE_CHANGED ChangeType = 9
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_ENTITY_CREATED",
		2: "CHANGE_TYPE_ENTITY_DELETED",
		3: "CHANGE_TYPE_ENTITY_IDENTITY_CHANGED",
		4: "CHANGE_TYPE_ENTITY_ATTRIBUTE_UPDATED",
		5: "CHANGE_TYPE_ENTITY_STATE_CHANGED",
		6: "CHANGE_TYPE_ENTITY_UNCHANGED",
		7: "CHANGE_TYPE_RELATION_ADDED",
		8: "CHANGE_TYPE_RELATION_REMOVED",
		9: "CHANGE_TYPE_RELATION_ATTRIBUTE_CHANGED",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED":                0,
		"CHANGE_TYPE_ENTITY_CREATED":             1,
		"CHANGE_TYPE_ENTITY_DELETED":             2,
		"CHANGE_TYPE_ENTITY_IDENTITY_CHANGED":    3,
		"CHANGE_TYPE_ENTITY_ATTRIBUTE_UPDATED":   4,
		"CHANGE_TYPE_ENTITY_STATE_CHANGED":       5,
		"CHANGE_TYPE_ENTITY_UNCHANGED":           6,
		"CHANGE_TYPE_RELATION_ADDED":             7,
		"CHANGE_TYPE_RELATION_REMOVED":           8,
		"CHANGE_TYPE_RELATION_ATTRIBUTE_CHANGED": 9,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_toise_v1_events_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_toise_v1_events_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{0}
}

// DeleteSource attributes the AUTHOR of a disappearance event: the producer
// (explicit delete, or an edge removed by absence on re-emit), Toise's liveness
// expiry (no heartbeat within entity.report.interval), or the cascade that
// removes incident edges when a node dies. It is consumer-authored provenance,
// deliberately distinct from delete_reason (which stays producer-supplied,
// verbatim): without it an expiry and a reason-less producer delete are
// indistinguishable on every read surface. UNSPECIFIED marks events written
// before this field existed — read it as "unknown", never as "producer".
type DeleteSource int32

const (
	DeleteSource_DELETE_SOURCE_UNSPECIFIED     DeleteSource = 0
	DeleteSource_DELETE_SOURCE_PRODUCER        DeleteSource = 1
	DeleteSource_DELETE_SOURCE_LIVENESS_EXPIRY DeleteSource = 2
	DeleteSource_DELETE_SOURCE_CASCADE         DeleteSource = 3
)

// Enum value maps for DeleteSource.
var (
	DeleteSource_name = map[int32]string{
		0: "DELETE_SOURCE_UNSPECIFIED",
		1: "DELETE_SOURCE_PRODUCER",
		2: "DELETE_SOURCE_LIVENESS_EXPIRY",
		3: "DELETE_SOURCE_CASCADE",
	}
	DeleteSource_value = map[string]int32{
		"DELETE_SOURCE_UNSPECIFIED":     0,
		"DELETE_SOURCE_PRODUCER":        1,
		"DELETE_SOURCE_LIVENESS_EXPIRY": 2,
		"DELETE_SOURCE_CASCADE":         3,
	}
)

func (x DeleteSource) Enum() *DeleteSource {
	p := new(DeleteSource)
	*p = x
	return p
}

func (x DeleteSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteSource) Descriptor() protoreflect.EnumDescriptor {
	return file_toise_v1_events_proto_enumTypes[1].Descriptor()
}

func (DeleteSource) Type() protoreflect.EnumType {
	return &file_toise_v1_events_proto_enumTypes[1]
}

func (x DeleteSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteSource.Descriptor instead.
func (DeleteSource) EnumDescriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{1}
}

// Value is a typed attribute value mirroring the OpenTelemetry AnyValue:
// the four scalars (string, int64, double, bool) plus recursive array and
// kvlist forms. Descriptive attributes (entity.description) carry the full
// AnyValue; identity values stay scalar by contract (ADR 0018). See ADR 0004.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_StringValue
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_BoolValue
	//	*Value_ArrayValue
	//	*Value_KvlistValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_toise_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_toise_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetArrayValue() *ArrayValue {
	if x != nil {
		if x, ok := x.Value.(*Value_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *Value) GetKvlistValue() *KeyValueList {
	if x != nil {
		if x, ok := x.Value.(*Value_KvlistValue); ok {
			return x.KvlistValue
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_ArrayValue struct {
	// array_value and kvlist_value are wrapper messages because a oneof field
	// cannot itself be `repeated` (this mirrors OTLP's ArrayValue/KeyValueList).
	ArrayValue *ArrayValue `protobuf:"bytes,5,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

type Value_KvlistValue struct {
	KvlistValue *KeyValueList `protobuf:"bytes,6,opt,name=kvlist_value,json=kvlistValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Value() {}

func (*Value_IntValue) isValue_Value() {}

func (*Value_DoubleValue) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_ArrayValue) isValue_Value() {}

func (*Value_KvlistValue) isValue_Value() {}

// ArrayValue is an ordered list of Values (the array AnyValue form).
type ArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_toise_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_toise_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *ArrayValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// KeyValueList is an ordered list of KeyValues (the kvlist/map AnyValue form).
type KeyValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*KeyValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueList) Reset() {
	*x = KeyValueList{}
	mi := &file_toise_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueList) ProtoMessage() {}

func (x *KeyValueList) ProtoReflect() protoreflect.Message {
	mi := &file_toise_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueList.ProtoReflect.Descriptor instead.
func (*KeyValueList) Descriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *KeyValueList) GetValues() []*KeyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// KeyValue is a single attribute.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_toise_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_toise_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Entity is an infrastructure entity aligned with the OpenTelemetry entity data
// model. See ADR 0004 and ADR 0017.
type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entity_id is the stable logical ID (a ULID), assigned on first sight and
	// stable across identity changes. See ADR 0017.
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// identity_hash is a deterministic hash (SHA-256, 128-bit, type-prefixed hex)
	// of the current identifying attributes. It changes when identity changes;
	// entity_id does not. See ADR 0017.
	IdentityHash string `protobuf:"bytes,2,opt,name=identity_hash,json=identityHash,proto3" json:"identity_hash,omitempty"`
	// type is the entity type, e.g. "host", "process". See ADR 0004.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// identity holds the identifying attributes (their values together identify
	// the entity).
	Identity []*KeyValue `protobuf:"bytes,4,rep,name=identity,proto3" json:"identity,omitempty"`
	// attributes holds descriptive (non-identifying) attributes.
	Attributes []*KeyValue `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// schema_url versions the entity definition.
	SchemaUrl     string `protobuf:"bytes,6,opt,name=schema_url,json=schemaUrl,proto3" json:"schema_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_toise_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_toise_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *Entity) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Entity) GetIdentityHash() string {
	if x != nil {
		return x.IdentityHash
	}
	return ""
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetIdentity() []*KeyValue {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Entity) GetAttributes() []*KeyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Entity) GetSchemaUrl() string {
	if x != nil {
		return x.SchemaUrl
	}
	return ""
}

// Relation is a typed directed edge between two entities. See ADR 0004.
type Relation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// relation_id is a deterministic hash of (type, from_entity_id, to_entity_id).
	RelationId string `protobuf:"bytes,1,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	Type       string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// from_entity_id and to_entity_id reference logical entity IDs.
	FromEntityId string      `protobuf:"bytes,3,opt,name=from_entity_id,json=fromEntityId,proto3" json:"from_entity_id,omitempty"`
	ToEntityId   string      `protobuf:"bytes,4,opt,name=to_entity_id,json=toEntityId,proto3" json:"to_entity_id,omitempty"`
	Attributes   []*KeyValue `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// structural indicates the relation's appearance/disappearance is significant
	// (suitable for alerting) rather than merely descriptive.
	Structural    bool `protobuf:"varint,6,opt,name=structural,proto3" json:"structural,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_toise_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_toise_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *Relation) GetRelationId() string {
	if x != nil {
		return x.RelationId
	}
	return ""
}

func (x *Relation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Relation) GetFromEntityId() string {
	if x != nil {
		return x.FromEntityId
	}
	return ""
}

func (x *Relation) GetToEntityId() string {
	if x != nil {
		return x.ToEntityId
	}
	return ""
}

func (x *Relation) GetAttributes() []*KeyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Relation) GetStructural() bool {
	if x != nil {
		return x.Structural
	}
	return false
}

// EntityEvent is a classified change about an entity. Bi-temporal: see ADR 0005.
type EntityEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id is a ULID identifying this event.
	EventId    string     `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ChangeType ChangeType `protobuf:"varint,2,opt,name=change_type,json=changeType,proto3,enum=toise.v1.ChangeType" json:"change_type,omitempty"`
	Entity     *Entity    `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	// event_time_unix_nano is when the fact became true in the real world,
	// provided by the producer.
	EventTimeUnixNano int64 `protobuf:"varint,4,opt,name=event_time_unix_nano,json=eventTimeUnixNano,proto3" json:"event_time_unix_nano,omitempty"`
	// recorded_at_unix_nano is when Toise recorded the event, set at ingestion.
	RecordedAtUnixNano int64 `protobuf:"varint,5,opt,name=recorded_at_unix_nano,json=recordedAtUnixNano,proto3" json:"recorded_at_unix_nano,omitempty"`
	// schema_version is the Toise schema version, e.g. "1.0".
	SchemaVersion string `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// changed_keys lists the attribute keys that changed, for
	// attribute_updated/state_changed events.
	ChangedKeys []string `protobuf:"bytes,7,rep,name=changed_keys,json=changedKeys,proto3" json:"changed_keys,omitempty"`
	// delete_reason is the producer-supplied motive for an entity.delete
	// (entity.delete.reason), an OPEN enum (free string, never a closed set on
	// Toise's side). Empty for non-delete events and for deletes that carried no
	// reason. See the OTel entity-events spec (1.58.0).
	DeleteReason string `protobuf:"bytes,8,opt,name=delete_reason,json=deleteReason,proto3" json:"delete_reason,omitempty"`
	// delete_source attributes the author of an entity_deleted event. Only
	// meaningful on deletes; UNSPECIFIED elsewhere and on pre-1.1 events.
	DeleteSource  DeleteSource `protobuf:"varint,9,opt,name=delete_source,json=deleteSource,proto3,enum=toise.v1.DeleteSource" json:"delete_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityEvent) Reset() {
	*x = EntityEvent{}
	mi := &file_toise_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityEvent) ProtoMessage() {}

func (x *EntityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_toise_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityEvent.ProtoReflect.Descriptor instead.
func (*EntityEvent) Descriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *EntityEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EntityEvent) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *EntityEvent) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *EntityEvent) GetEventTimeUnixNano() int64 {
	if x != nil {
		return x.EventTimeUnixNano
	}
	return 0
}

func (x *EntityEvent) GetRecordedAtUnixNano() int64 {
	if x != nil {
		return x.RecordedAtUnixNano
	}
	return 0
}

func (x *EntityEvent) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EntityEvent) GetChangedKeys() []string {
	if x != nil {
		return x.ChangedKeys
	}
	return nil
}

func (x *EntityEvent) GetDeleteReason() string {
	if x != nil {
		return x.DeleteReason
	}
	return ""
}

func (x *EntityEvent) GetDeleteSource() DeleteSource {
	if x != nil {
		return x.DeleteSource
	}
	return DeleteSource_DELETE_SOURCE_UNSPECIFIED
}

// RelationEvent is a classified change about a relation. Bi-temporal: ADR 0005.
type RelationEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EventId            string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ChangeType         ChangeType             `protobuf:"varint,2,opt,name=change_type,json=changeType,proto3,enum=toise.v1.ChangeType" json:"change_type,omitempty"`
	Relation           *Relation              `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	EventTimeUnixNano  int64                  `protobuf:"varint,4,opt,name=event_time_unix_nano,json=eventTimeUnixNano,proto3" json:"event_time_unix_nano,omitempty"`
	RecordedAtUnixNano int64                  `protobuf:"varint,5,opt,name=recorded_at_unix_nano,json=recordedAtUnixNano,proto3" json:"recorded_at_unix_nano,omitempty"`
	SchemaVersion      string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ChangedKeys        []string               `protobuf:"bytes,7,rep,name=changed_keys,json=changedKeys,proto3" json:"changed_keys,omitempty"`
	// delete_source attributes the author of a relation_removed event: an
	// explicit/absence removal by the producer, the cascade of a dying endpoint,
	// or a per-edge liveness expiry. Relations previously had NO discriminant at
	// all — the same relation_removed covered all three origins.
	DeleteSource  DeleteSource `protobuf:"varint,8,opt,name=delete_source,json=deleteSource,proto3,enum=toise.v1.DeleteSource" json:"delete_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationEvent) Reset() {
	*x = RelationEvent{}
	mi := &file_toise_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationEvent) ProtoMessage() {}

func (x *RelationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_toise_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationEvent.ProtoReflect.Descriptor instead.
func (*RelationEvent) Descriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *RelationEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RelationEvent) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *RelationEvent) GetRelation() *Relation {
	if x != nil {
		return x.Relation
	}
	return nil
}

func (x *RelationEvent) GetEventTimeUnixNano() int64 {
	if x != nil {
		return x.EventTimeUnixNano
	}
	return 0
}

func (x *RelationEvent) GetRecordedAtUnixNano() int64 {
	if x != nil {
		return x.RecordedAtUnixNano
	}
	return 0
}

func (x *RelationEvent) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RelationEvent) GetChangedKeys() []string {
	if x != nil {
		return x.ChangedKeys
	}
	return nil
}

func (x *RelationEvent) GetDeleteSource() DeleteSource {
	if x != nil {
		return x.DeleteSource
	}
	return DeleteSource_DELETE_SOURCE_UNSPECIFIED
}

// Event is the envelope stored in the append-only event log.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_EntityEvent
	//	*Event_RelationEvent
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_toise_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_toise_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_toise_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetEntityEvent() *EntityEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_EntityEvent); ok {
			return x.EntityEvent
		}
	}
	return nil
}

func (x *Event) GetRelationEvent() *RelationEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_RelationEvent); ok {
			return x.RelationEvent
		}
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_EntityEvent struct {
	EntityEvent *EntityEvent `protobuf:"bytes,1,opt,name=entity_event,json=entityEvent,proto3,oneof"`
}

type Event_RelationEvent struct {
	RelationEvent *RelationEvent `protobuf:"bytes,2,opt,name=relation_event,json=relationEvent,proto3,oneof"`
}

func (*Event_EntityEvent) isEvent_Event() {}

func (*Event_RelationEvent) isEvent_Event() {}

var File_toise_v1_events_proto protoreflect.FileDescriptor

const file_toise_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x15toise/v1/events.proto\x12\btoise.v1\"\x90\x02\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x127\n" +
	"\varray_value\x18\x05 \x01(\v2\x14.toise.v1.ArrayValueH\x00R\n" +
	"arrayValue\x12;\n" +
	"\fkvlist_value\x18\x06 \x01(\v2\x16.toise.v1.KeyValueListH\x00R\vkvlistValueB\a\n" +
	"\x05value\"5\n" +
	"\n" +
	"ArrayValue\x12'\n" +
	"\x06values\x18\x01 \x03(\v2\x0f.toise.v1.ValueR\x06values\":\n" +
	"\fKeyValueList\x12*\n" +
	"\x06values\x18\x01 \x03(\v2\x12.toise.v1.KeyValueR\x06values\"C\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.toise.v1.ValueR\x05value\"\xe1\x01\n" +
	"\x06Entity\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12#\n" +
	"\ridentity_hash\x18\x02 \x01(\tR\fidentityHash\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12.\n" +
	"\bidentity\x18\x04 \x03(\v2\x12.toise.v1.KeyValueR\bidentity\x122\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2\x12.toise.v1.KeyValueR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"schema_url\x18\x06 \x01(\tR\tschemaUrl\"\xdb\x01\n" +
	"\bRelation\x12\x1f\n" +
	"\vrelation_id\x18\x01 \x01(\tR\n" +
	"relationId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12$\n" +
	"\x0efrom_entity_id\x18\x03 \x01(\tR\ffromEntityId\x12 \n" +
	"\fto_entity_id\x18\x04 \x01(\tR\n" +
	"toEntityId\x122\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2\x12.toise.v1.KeyValueR\n" +
	"attributes\x12\x1e\n" +
	"\n" +
	"structural\x18\x06 \x01(\bR\n" +
	"structural\"\x99\x03\n" +
	"\vEntityEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x125\n" +
	"\vchange_type\x18\x02 \x01(\x0e2\x14.toise.v1.ChangeTypeR\n" +
	"changeType\x12(\n" +
	"\x06entity\x18\x03 \x01(\v2\x10.toise.v1.EntityR\x06entity\x12/\n" +
	"\x14event_time_unix_nano\x18\x04 \x01(\x03R\x11eventTimeUnixNano\x121\n" +
	"\x15recorded_at_unix_nano\x18\x05 \x01(\x03R\x12recordedAtUnixNano\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x12!\n" +
	"\fchanged_keys\x18\a \x03(\tR\vchangedKeys\x12#\n" +
	"\rdelete_reason\x18\b \x01(\tR\fdeleteReason\x12;\n" +
	"\rdelete_source\x18\t \x01(\x0e2\x16.toise.v1.DeleteSourceR\fdeleteSource\"\xfc\x02\n" +
	"\rRelationEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x125\n" +
	"\vchange_type\x18\x02 \x01(\x0e2\x14.toise.v1.ChangeTypeR\n" +
	"changeType\x12.\n" +
	"\brelation\x18\x03 \x01(\v2\x12.toise.v1.RelationR\brelation\x12/\n" +
	"\x14event_time_unix_nano\x18\x04 \x01(\x03R\x11eventTimeUnixNano\x121\n" +
	"\x15recorded_at_unix_nano\x18\x05 \x01(\x03R\x12recordedAtUnixNano\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x12!\n" +
	"\fchanged_keys\x18\a \x03(\tR\vchangedKeys\x12;\n" +
	"\rdelete_source\x18\b \x01(\x0e2\x16.toise.v1.DeleteSourceR\fdeleteSource\"\x8e\x01\n" +
	"\x05Event\x12:\n" +
	"\fentity_event\x18\x01 \x01(\v2\x15.toise.v1.EntityEventH\x00R\ventityEvent\x12@\n" +
	"\x0erelation_event\x18\x02 \x01(\v2\x17.toise.v1.RelationEventH\x00R\rrelationEventB\a\n" +
	"\x05event*\xf2\x02\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCHANGE_TYPE_ENTITY_CREATED\x10\x01\x12\x1e\n" +
	"\x1aCHANGE_TYPE_ENTITY_DELETED\x10\x02\x12'\n" +
	"#CHANGE_TYPE_ENTITY_IDENTITY_CHANGED\x10\x03\x12(\n" +
	"$CHANGE_TYPE_ENTITY_ATTRIBUTE_UPDATED\x10\x04\x12$\n" +
	" CHANGE_TYPE_ENTITY_STATE_CHANGED\x10\x05\x12 \n" +
	"\x1cCHANGE_TYPE_ENTITY_UNCHANGED\x10\x06\x12\x1e\n" +
	"\x1aCHANGE_TYPE_RELATION_ADDED\x10\a\x12 \n" +
	"\x1cCHANGE_TYPE_RELATION_REMOVED\x10\b\x12*\n" +
	"&CHANGE_TYPE_RELATION_ATTRIBUTE_CHANGED\x10\t*\x87\x01\n" +
	"\fDeleteSource\x12\x1d\n" +
	"\x19DELETE_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DELETE_SOURCE_PRODUCER\x10\x01\x12!\n" +
	"\x1dDELETE_SOURCE_LIVENESS_EXPIRY\x10\x02\x12\x19\n" +
	"\x15DELETE_SOURCE_CASCADE\x10\x03B3Z1github.com/toise-dev/toise/proto/toise/v1;toisev1b\x06proto3"

var (
	file_toise_v1_events_proto_rawDescOnce sync.Once
	file_toise_v1_events_proto_rawDescData []byte
)

func file_toise_v1_events_proto_rawDescGZIP() []byte {
	file_toise_v1_events_proto_rawDescOnce.Do(func() {
		file_toise_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_toise_v1_events_proto_rawDesc), len(file_toise_v1_events_proto_rawDesc)))
	})
	return file_toise_v1_events_proto_rawDescData
}

var file_toise_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_toise_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_toise_v1_events_proto_goTypes = []any{
	(ChangeType)(0),       // 0: toise.v1.ChangeType
	(DeleteSource)(0),     // 1: toise.v1.DeleteSource
	(*Value)(nil),         // 2: toise.v1.Value
	(*ArrayValue)(nil),    // 3: toise.v1.ArrayValue
	(*KeyValueList)(nil),  // 4: toise.v1.KeyValueList
	(*KeyValue)(nil),      // 5: toise.v1.KeyValue
	(*Entity)(nil),        // 6: toise.v1.Entity
	(*Relation)(nil),      // 7: toise.v1.Relation
	(*EntityEvent)(nil),   // 8: toise.v1.EntityEvent
	(*RelationEvent)(nil), // 9: toise.v1.RelationEvent
	(*Event)(nil),         // 10: toise.v1.Event
}
var file_toise_v1_events_proto_depIdxs = []int32{
	3,  // 0: toise.v1.Value.array_value:type_name -> toise.v1.ArrayValue
	4,  // 1: toise.v1.Value.kvlist_value:type_name -> toise.v1.KeyValueList
	2,  // 2: toise.v1.ArrayValue.values:type_name -> toise.v1.Value
	5,  // 3: toise.v1.KeyValueList.values:type_name -> toise.v1.KeyValue
	2,  // 4: toise.v1.KeyValue.value:type_name -> toise.v1.Value
	5,  // 5: toise.v1.Entity.identity:type_name -> toise.v1.KeyValue
	5,  // 6: toise.v1.Entity.attributes:type_name -> toise.v1.KeyValue
	5,  // 7: toise.v1.Relation.attributes:type_name -> toise.v1.KeyValue
	0,  // 8: toise.v1.EntityEvent.change_type:type_name -> toise.v1.ChangeType
	6,  // 9: toise.v1.EntityEvent.entity:type_name -> toise.v1.Entity
	1,  // 10: toise.v1.EntityEvent.delete_source:type_name -> toise.v1.DeleteSource
	0,  // 11: toise.v1.RelationEvent.change_type:type_name -> toise.v1.ChangeType
	7,  // 12: toise.v1.RelationEvent.relation:type_name -> toise.v1.Relation
	1,  // 13: toise.v1.RelationEvent.delete_source:type_name -> toise.v1.DeleteSource
	8,  // 14: toise.v1.Event.entity_event:type_name -> toise.v1.EntityEvent
	9,  // 15: toise.v1.Event.relation_event:type_name -> toise.v1.RelationEvent
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_toise_v1_events_proto_init() }
func file_toise_v1_events_proto_init() {
	if File_toise_v1_events_proto != nil {
		return
	}
	file_toise_v1_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_ArrayValue)(nil),
		(*Value_KvlistValue)(nil),
	}
	file_toise_v1_events_proto_msgTypes[8].OneofWrappers = []any{
		(*Event_EntityEvent)(nil),
		(*Event_RelationEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_toise_v1_events_proto_rawDesc), len(file_toise_v1_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_toise_v1_events_proto_goTypes,
		DependencyIndexes: file_toise_v1_events_proto_depIdxs,
		EnumInfos:         file_toise_v1_events_proto_enumTypes,
		MessageInfos:      file_toise_v1_events_proto_msgTypes,
	}.Build()
	File_toise_v1_events_proto = out.File
	file_toise_v1_events_proto_goTypes = nil
	file_toise_v1_events_proto_depIdxs = nil
}
